book_names_mapping = {
    "Sahih al Bukhari": {
        "Revelation": "كتاب بدء الوحى",
        "Belief": "كتاب الإيمان",
        "Knowledge": "كتاب العلم",
        "Ablutions (Wudu')": "كتاب الوضوء",
        "Bathing (Ghusl)": "كتاب الغسل",
        "Menstrual Periods": "كتاب الحيض",
        "Rubbing hands and feet with dust (Tayammum)": "كتاب التيمم",
        "Prayers (Salat)": "كتاب الصلاة",
        "Times of the Prayers": "كتاب مواقيت الصلاة",
        "Call to Prayers (Adhaan)": "كتاب الأذان",
        "Friday Prayer": "كتاب الجمعة",
        "Fear Prayer": "كتاب صلاة الخوف",
        "The Two Festivals (Eids)": "كتاب العيدين",
        "Witr Prayer": "كتاب الوتر",
        "Invoking Allah for Rain (Istisqaa)": "كتاب الاستسقاء",
        "Eclipses": "كتاب الكسوف",
        "Prostration During Recital of Qur'an": "كتاب سجود القرآن",
        "Shortening the Prayers (At-Taqseer)": "كتاب التقصير",
        "Prayer at Night (Tahajjud)": "كتاب التهجد",
        "Virtues of Prayer at Masjid Makkah and Madinah": "كتاب فضل الصلاة فى مسجد مكة والمدينة",
        "Actions while Praying": "كتاب العمل فى الصلاة",
        "Forgetfulness in Prayer": "كتاب السهو",
        "Funerals (Al-Janaa'iz)": "كتاب الجنائز",
        "Obligatory Charity Tax (Zakat)": "كتاب الزكاة",
        "Hajj (Pilgrimage)": "كتاب الحج",
        "`Umrah (Minor pilgrimage)": "كتاب العمرة",
        "Pilgrims Prevented from Completing the Pilgrimage": "كتاب المحصر",
        "Penalty of Hunting while on Pilgrimage": "كتاب جزاء الصيد",
        "Virtues of Madinah": "كتاب فضائل المدينة",
        "Fasting": "كتاب الصوم",
        "Praying at Night in Ramadaan (Taraweeh)": "كتاب صلاة التراويح",
        "Virtues of the Night of Qadr": "كتاب فضل ليلة القدر",
        "Retiring to a Mosque for Remembrance of Allah (I'tikaf)": "كتاب الاعتكاف",
        "Sales and Trade": "كتاب البيوع",
        "Sales in which a Price is paid for Goods to be Delivered Later (As-Salam)": "كتاب السلم",
        "Shuf'a": "كتاب الشفعة",
        "Hiring": "كتاب الإجارة",
        "Transferance of a Debt from One Person to Another (Al-Hawaala)": "كتاب الحوالات",
        "Kafalah": "كتاب الكفالة",
        "Representation, Authorization, Business by Proxy": "كتاب الوكالة",
        "Agriculture": "كتاب المزارعة",
        "Distribution of Water": "كتاب المساقاة",
        "Loans, Payment of Loans, Freezing of Property, Bankruptcy": "كتاب فى الاستقراض",
        "Khusoomaat": "كتاب الخصومات",
        "Lost Things Picked up by Someone (Luqatah)": "كتاب فى اللقطة",
        "Oppressions": "كتاب المظالم",
        "Partnership": "كتاب الشركة",
        "Mortgaging": "كتاب الرهن",
        "Manumission of Slaves": "كتاب العتق",
        "Makaatib": "كتاب المكاتب",
        "Gifts": "كتاب الهبة وفضلها والتحريض عليها",
        "Witnesses": "كتاب الشهادات",
        "Peacemaking": "كتاب الصلح",
        "Conditions": "كتاب الشروط",
        "Wills and Testaments (Wasaayaa)": "كتاب الوصايا",
        "Fighting for the Cause of Allah (Jihaad)": "كتاب الجهاد والسير",
        "One-fifth of Booty to the Cause of Allah (Khumus)": "كتاب فرض الخمس",
        "Jizyah and Mawaada'ah": "كتاب الجزية والموادعة",
        "Beginning of Creation": "كتاب بدء الخلق",
        "Prophets": "كتاب أحاديث الأنبياء",
        "Virtues and Merits of the Prophet (pbuh) and his Companions": "كتاب المناقب",
        "Companions of the Prophet": "كتاب فضائل أصحاب النبى صلى الله عليه وسلم",
        "Merits of the Helpers in Madinah (Ansaar)": "كتاب مناقب الأنصار",
        "Military Expeditions led by the Prophet (pbuh) (Al-Maghaazi)": "كتاب المغازى",
        "Prophetic Commentary on the Qur'an (Tafseer of the Prophet (pbuh))": "كتاب التفسير",
        "Virtues of the Qur'an": "كتاب فضائل القرآن",
        "Wedlock, Marriage (Nikaah)": "كتاب النكاح",
        "Divorce": "كتاب الطلاق",
        "Supporting the Family": "كتاب النفقات",
        "Food, Meals": "كتاب الأطعمة",
        "Sacrifice on Occasion of Birth (`Aqiqa)": "كتاب العقيقة",
        "Hunting, Slaughtering": "كتاب الذبائح والصيد",
        "Al-Adha Festival Sacrifice (Adaahi)": "كتاب الأضاحي",
        "Drinks": "كتاب الأشربة",
        "Patients": "كتاب المرضى",
        "Medicine": "كتاب الطب",
        "Dress": "كتاب اللباس",
        "Good Manners and Form (Al-Adab)": "كتاب الأدب",
        "Asking Permission": "كتاب الاستئذان",
        "Invocations": "كتاب الدعوات",
        "To make the Heart Tender (Ar-Riqaq)": "كتاب الرقاق",
        "Divine Will (Al-Qadar)": "كتاب القدر",
        "Oaths and Vows": "كتاب الأيمان والنذور",
        "Expiation for Unfulfilled Oaths": "كتاب كفارات الأيمان",
        "Laws of Inheritance (Al-Faraa'id)": "كتاب الفرائض",
        "Limits and Punishments set by Allah (Hudood)": "كتاب الحدود",
        "Blood Money (Ad-Diyat)": "كتاب الديات",
        "Apostates": "كتاب استتابة المرتدين والمعاندين وقتالهم",
        "(Statements made under) Coercion": "كتاب الإكراه",
        "Tricks": "كتاب الحيل",
        "Interpretation of Dreams": "كتاب التعبير",
        "Afflictions and the End of the World": "كتاب الفتن",
        "Judgments (Ahkaam)": "كتاب الأحكام",
        "Wishes": "كتاب التمنى",
        "Accepting Information Given by a Truthful Person": "كتاب أخبار الآحاد",
        "Holding Fast to the Qur'an and Sunnah": "كتاب الاعتصام بالكتاب والسنة",
        "Oneness, Uniqueness of Allah (Tawheed)": "كتاب التوحيد",
    },
    "Sahih Muslim": {
        "The Book of Faith": "كتاب الإيمان",
        "The Book of Purification": "كتاب الطهارة",
        "The Book of Menstruation": "كتاب الحيض",
        "The Book of Prayers": "كتاب الصلاة",
        "The Book of Mosques and Places of Prayer": "كتاب الْمَسَاجِدِ وَمَوَاضِعِ الصَّلاَةِ",
        "The Book of Prayer - Travellers": "كتاب صلاة المسافرين وقصرها",
        "The Book of Prayer - Friday": "كتاب الجمعة",
        "The Book of Prayer - Two Eids": "كتاب صلاة العيدين",
        "The Book of Prayer - Rain": "كتاب صلاة الاستسقاء\u200f",
        "The Book of Prayer - Eclipses": "كتاب الكسوف",
        "The Book of Prayer - Funerals": "كتاب الجنائز",
        "The Book of Zakat": "كتاب الزكاة",
        "The Book of Fasting": "كتاب الصيام",
        "The Book of I'tikaf": "كتاب الاعتكاف",
        "The Book of Pilgrimage": "كتاب الحج",
        "The Book of Marriage": "كتاب النكاح",
        "The Book of Suckling": "كتاب الرضاع",
        "The Book of Divorce": "كتاب الطلاق",
        "The Book of Invoking Curses": "كتاب اللعان",
        "The Book of Emancipating Slaves": "كتاب العتق",
        "The Book of Transactions": "كتاب البيوع",
        "The Book of Musaqah": "كتاب المساقاة",
        "The Book of the Rules of Inheritance": "كتاب الفرائض",
        "The Book of Gifts": "كتاب الهبات",
        "The Book of Wills": "كتاب الوصية",
        "The Book of Vows": "كتاب النذر",
        "The Book of Oaths": "كتاب الأيمان",
        "The Book of Oaths, Muharibin, Qasas (Retaliation), and Diyat (Blood Money)": "كتاب القسامة والمحاربين والقصاص والديات",
        "The Book of Legal Punishments": "كتاب الحدود",
        "The Book of Judicial Decisions": "كتاب الأقضية",
        "The Book of Lost Property": "كتاب اللقطة",
        "The Book of Jihad and Expeditions": "كتاب الجهاد والسير",
        "The Book on Government": "كتاب الإمارة",
        "The Book of Hunting, Slaughter, and what may be Eaten": "كتاب الصيد والذبائح وما يؤكل من الحيوان",
        "The Book of Sacrifices": "كتاب الأضاحى",
        "The Book of Drinks": "كتاب الأشربة",
        "The Book of Clothes and Adornment": "كتاب اللباس والزينة",
        "The Book of Manners and Etiquette": "كتاب الآداب",
        "The Book of Greetings": "كتاب السلام",
        "The Book Concerning the Use of Correct Words": "كتاب الألفاظ من الأدب وغيرها",
        "The Book of Poetry": "كتاب الشعر",
        "The Book of Dreams": "كتاب الرؤيا",
        "The Book of Virtues": "كتاب الفضائل",
        "The Book of the Merits of the Companions": "كتاب فضائل الصحابة رضى الله تعالى عنهم",
        "The Book of Virtue, Enjoining Good Manners, and Joining of the Ties of Kinship": "كتاب البر والصلة والآداب",
        "The Book of Destiny": "كتاب القدر",
        "The Book of Knowledge": "كتاب العلم",
        "The Book Pertaining to the Remembrance of Allah, Supplication, Repentance and Seeking Forgiveness": "كتاب الذكر والدعاء والتوبة والاستغفار",
        "The Book of Heart-Melting Traditions": "كتاب الرقاق",
        "The Book of Repentance": "كتاب التوبة",
        "Characteristics of The Hypocrites And Rulings Concerning Them": "كتاب صفات المنافقين وأحكامهم",
        "Characteristics of the Day of Judgment, Paradise, and Hell": "كتاب صفة القيامة والجنة والنار",
        "The Book of Paradise, its Description, its Bounties and its Inhabitants": "كتاب الجنة وصفة نعيمها وأهلها",
        "The Book of Tribulations and Portents of the Last Hour": "كتاب الفتن وأشراط الساعة",
        "The Book of Zuhd and Softening of Hearts": "كتاب الزهد والرقائق",
        "The Book of Commentary on the Qur'an": "كتاب التفسير",
    },
    "Sunan an Nasai": {
        "The Book of Purification": "كتاب الطهارة",
        "The Book of Water": "كتاب المياه",
        "The Book of Menstruation and Istihadah": "كتاب الحيض والاستحاضة",
        "The Book of Ghusl and Tayammum": "كتاب الغسل والتيمم",
        "The Book of Salah": "كتاب الصلاة",
        "The Book of the Times (of Prayer)": "كتاب المواقيت",
        "The Book of the Adhan (The Call to Prayer)": "كتاب الأذان",
        "The Book of the Masjids": "كتاب المساجد",
        "The Book of the Qiblah": "كتاب القبلة",
        "The Book of Leading the Prayer (Al-Imamah)": "كتاب الإمامة",
        "The Book of the Commencement of the Prayer": "كتاب الافتتاح",
        "The Book of The At-Tatbiq (Clasping One's Hands Together)": "كتاب التطبيق",
        "The Book of Forgetfulness (In Prayer)": "كتاب السهو",
        "The Book of Jumu'ah (Friday Prayer)": "كتاب الجمعة",
        "The Book of Shortening the Prayer When Traveling": "كتاب تقصير الصلاة فى السفر",
        "The Book of Eclipses": "كتاب الكسوف",
        "The Book of Praying for Rain (Al-Istisqa')": "كتاب الاستسقاء",
        "The Book of the Fear Prayer": "كتاب صلاة الخوف",
        "The Book of the Prayer for the Two 'Eids": "كتاب صلاة العيدين",
        "The Book of Qiyam Al-Lail (The Night Prayer) and Voluntary Prayers During the Day": "كتاب قيام الليل وتطوع النهار",
        "The Book of Funerals": "كتاب الجنائز",
        "The Book of Fasting": "كتاب الصيام",
        "The Book of Zakah": "كتاب الزكاة",
        "The Book of Hajj": "كتاب مناسك الحج",
        "The Book of Jihad": "كتاب الجهاد",
        "The Book of Marriage": "كتاب النكاح",
        "The Book of Divorce": "كتاب الطلاق",
        "The Book of Horses, Races and Shooting": "كتاب الخيل",
        "The Book of Endowments": "كتاب الإحباس",
        "The Book of Wills": "كتاب الوصايا",
        "The Book of Presents": "كتاب النحل",
        "The Book of Gifts": "كتاب الهبة",
        "The Book of ar-Ruqba": "كتاب الرقبى",
        "The Book of 'Umra": "كتاب العمرى",
        "The Book of Oaths and Vows": "كتاب الأيمان والنذور",
        "The Book of Agriculture": "كتاب المزارعة",
        "The Book of the Kind Treatment of Women": "كتاب عشرة النساء",
        "The Book of Fighting [The Prohibition of Bloodshed]": "كتاب تحريم الدم",
        "The Book of Distribution of Al-Fay'": "كتاب قسم الفىء",
        "The Book of al-Bay'ah": "كتاب البيعة",
        "The Book of al-'Aqiqah": "كتاب العقيقة",
        "The Book of al-Fara' and al-'Atirah": "كتاب الفرع والعتيرة",
        "The Book of Hunting and Slaughtering": "كتاب الصيد والذبائح",
        "The Book of ad-Dahaya (Sacrifices)": "كتاب الضحايا",
        "The Book of Financial Transactions": "كتاب البيوع",
        "The Book of Oaths (qasamah), Retaliation and Blood Money": "كتاب القسامة",
        "The Book of Cutting off the Hand of the Thief": "كتاب قطع السارق",
        "The Book Of Faith and its Signs": "كتاب الإيمان وشرائعه",
        "The Book of Adornment": "كتاب الزينة من السنن",
        "The Book of the Etiquette of Judges": "كتاب آداب القضاة",
        "The Book of Seeking Refuge with Allah": "كتاب الاستعاذة",
        "The Book of Drinks": "كتاب الأشربة",
    },
    "Sunan Abu Dawud": {
        "Purification (Kitab Al-Taharah)": "كتاب الطهارة",
        "Prayer (Kitab Al-Salat)": "كتاب الصلاة",
        "The Book Of The Prayer For Rain (Kitab al-Istisqa')": "كتاب الاستسقاء",
        "Prayer (Kitab Al-Salat): Detailed Rules of Law about the Prayer during Journey": "كتاب صلاة السفر",
        "Prayer (Kitab Al-Salat): Voluntary Prayers": "كتاب التطوع",
        "Prayer (Kitab Al-Salat): Detailed Injunctions about Ramadan": "كتاب شهر رمضان",
        "Prayer (Kitab Al-Salat): Prostration while reciting the Qur'an": "كتاب سجود القرآن",
        "Prayer (Kitab Al-Salat): Detailed Injunctions about Witr": "كتاب الوتر",
        "Zakat (Kitab Al-Zakat)": "كتاب الزكاة",
        "The Book of Lost and Found Items": "كتاب اللقطة",
        "The Rites of Hajj (Kitab Al-Manasik Wa'l-Hajj)": "كتاب المناسك",
        "Marriage (Kitab Al-Nikah)": "كتاب النكاح",
        "Divorce (Kitab Al-Talaq)": "كتاب الطلاق",
        "Fasting (Kitab Al-Siyam)": "كتاب الصوم",
        "Jihad (Kitab Al-Jihad)": "كتاب الجهاد",
        "Sacrifice (Kitab Al-Dahaya)": "كتاب الضحايا",
        "Game (Kitab Al-Said)": "كتاب الصيد",
        "Wills (Kitab Al-Wasaya)": "كتاب الوصايا",
        "Shares of Inheritance (Kitab Al-Fara'id)": "كتاب الفرائض",
        "Tribute, Spoils, and Rulership (Kitab Al-Kharaj, Wal-Fai' Wal-Imarah)": "كتاب الخراج والإمارة والفىء",
        "Funerals (Kitab Al-Jana'iz)": "كتاب الجنائز",
        "Oaths and Vows (Kitab Al-Aiman Wa Al-Nudhur)": "كتاب الأيمان والنذور",
        "Commercial Transactions (Kitab Al-Buyu)": "كتاب البيوع",
        "Wages (Kitab Al-Ijarah)": "كتاب الإجارة",
        "The Office of the Judge (Kitab Al-Aqdiyah)": "كتاب الأقضية",
        "Knowledge (Kitab Al-Ilm)": "كتاب العلم",
        "Drinks (Kitab Al-Ashribah)": "كتاب الأشربة",
        "Foods (Kitab Al-At'imah)": "كتاب الأطعمة",
        "Medicine (Kitab Al-Tibb)": "كتاب الطب",
        "Divination and Omens (Kitab Al-Kahanah Wa Al-Tatayyur)": "كتاب الكهانة و التطير",
        "The Book of Manumission of Slaves": "كتاب العتق",
        "Dialects and Readings of the Qur'an (Kitab Al-Huruf Wa Al-Qira'at)": "كتاب الحروف والقراءات",
        "Hot Baths (Kitab Al-Hammam)": "كتاب الحمَّام",
        "Clothing (Kitab Al-Libas)": "كتاب اللباس",
        "Combing the Hair (Kitab Al-Tarajjul)": "كتاب الترجل",
        "Signet-Rings (Kitab Al-Khatam)": "كتاب الخاتم",
        "Trials and Fierce Battles (Kitab Al-Fitan Wa Al-Malahim)": "كتاب الفتن والملاحم",
        "The Promised Deliverer (Kitab Al-Mahdi)": "كتاب المهدى",
        "Battles (Kitab Al-Malahim)": "كتاب الملاحم",
        "Prescribed Punishments (Kitab Al-Hudud)": "كتاب الحدود",
        "Types of Blood-Wit (Kitab Al-Diyat)": "كتاب الديات",
        "Model Behavior of the Prophet (Kitab Al-Sunnah)": "كتاب السنة",
        "General Behavior (Kitab Al-Adab)": "كتاب الأدب",
    },
    "Jami At Tirmidhi": {
        "The Book on Purification": "كتاب الطهارة عن رسول الله صلى الله عليه وسلم",
        "The Book on Salat (Prayer)": "كتاب الصلاة",
        "The Book on Al-Witr": "أَبْوَابُ الْوِتْرِ",
        "The Book on the Day of Friday": "كِتَاب الْجُمُعَةِ عَنْ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ",
        "The Book on the Two Eids": "أَبْوَابُ الْعِيدَيْنِ عَنْ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ",
        "The Book on Traveling": "أَبْوَابُ السَّفَرِ",
        "The Book on Zakat": "كتاب الزكاة عن رسول الله صلى الله عليه وسلم",
        "The Book on Fasting": "كتاب الصوم عن رسول الله صلى الله عليه وسلم",
        "The Book on Hajj": "كتاب الحج عن رسول الله صلى الله عليه وسلم",
        "The Book on Jana''iz (Funerals)": "كتاب الجنائز عن رسول الله صلى الله عليه وسلم",
        "The Book on Marriage": "كتاب النكاح عن رسول الله صلى الله عليه وسلم",
        "The Book on Suckling": "كتاب الرضاع",
        "The Book on Divorce and Li'an": "كتاب الطلاق واللعان عن رسول الله صلى الله عليه وسلم",
        "The Book on Business": "كتاب البيوع عن رسول الله صلى الله عليه وسلم",
        "The Chapters On Judgements From The Messenger of Allah": "كتاب الأحكام عن رسول الله صلى الله عليه وسلم",
        "The Book on Blood Money": "كتاب الديات عن رسول الله صلى الله عليه وسلم",
        "The Book on Legal Punishments (Al-Hudud)": "كتاب الحدود عن رسول الله صلى الله عليه وسلم",
        "The Book on Hunting": "كتاب الصيد والذبائح عن رسول الله صلى الله عليه وسلم",
        "The Book on Sacrifices": "كتاب الأضاحى عن رسول الله صلى الله عليه وسلم",
        "The Book on Vows and Oaths": "كتاب النذور والأيمان عن رسول الله صلى الله عليه وسلم",
        "The Book on Military Expeditions": "كتاب السير عن رسول الله صلى الله عليه وسلم",
        "The Book on Virtues of Jihad": "كتاب فضائل الجهاد عن رسول الله صلى الله عليه وسلم",
        "The Book on Jihad": "كتاب الجهاد عن رسول الله صلى الله عليه وسلم",
        "The Book on Clothing": "كتاب اللباس",
        "The Book on Food": "كتاب الأطعمة عن رسول الله صلى الله عليه وسلم",
        "The Book on Drinks": "كتاب الأشربة عن رسول الله صلى الله عليه وسلم",
        "Chapters on Righteousness And Maintaining Good Relations With Relatives": "كتاب البر والصلة عن رسول الله صلى الله عليه وسلم",
        "Chapters on Medicine": "كتاب الطب عن رسول اللَّهِ صلى الله عليه وسلم",
        "Chapters On Inheritance": "كتاب الفرائض عن رسول الله صلى الله عليه وسلم",
        "Chapters On Wasaya (Wills and Testament)": "كتاب الوصايا عن رسول الله صلى الله عليه وسلم",
        "Chapters On Wala' And Gifts": "كتاب الولاء والهبة عن رسول الله صلى الله عليه وسلم",
        "Chapters On Al-Qadar": "كتاب القدر عن رسول الله صلى الله عليه وسلم",
        "Chapters On Al-Fitan": "كتاب الفتن عن رسول الله صلى الله عليه وسلم",
        "Chapters On Dreams": "كتاب الرؤيا عن رسول الله صلى الله عليه وسلم",
        "Chapters On Witnesses": "كتاب الشهادات عن رسول الله صلى الله عليه وسلم",
        "Chapters On Zuhd": "كتاب الزهد عن رسول الله صلى الله عليه وسلم",
        "Chapters on the description of the Day of Judgement, Ar-Riqaq, and Al-Wara'": "كتاب صفة القيامة والرقائق والورع عن رسول الله صلى الله",
        "Chapters on the description of Paradise": "كتاب صفة الجنة عن رسول الله صلى الله عليه وسلم",
        "The Book on the Description of Hellfire": "كتاب صفة جهنم عن رسول الله صلى الله عليه وسلم",
        "The Book on Faith": "كتاب الإيمان عن رسول الله صلى الله عليه وسلم",
        "Chapters on Knowledge": "كتاب العلم عن رسول الله صلى الله عليه وسلم",
        "Chapters on Seeking Permission": "كتاب الاستئذان والآداب عن رسول الله صلى الله عليه وسلم",
        "Chapters on Manners": "كتاب الأدب عن رسول الله صلى الله عليه وسلم",
        "Chapters on Parables": "كتاب الأمثال عن رسول الله صلى الله عليه وسلم",
        "Chapters on The Virtues of the Qur'an": "كتاب ثواب القرآن عن رسول الله صلى الله عليه وسلم",
        "Chapters on Recitation": "كتاب القراءات عن رسول الله صلى الله عليه وسلم",
        "Chapters on Tafsir": "كتاب تفسير القرآن عن رسول الله صلى الله عليه وسلم",
        "Chapters on Supplication": "كتاب الدعوات عن رسول الله صلى الله عليه وسلم",
        "Chapters on Virtues": "كتاب المناقب عن رسول الله صلى الله عليه وسلم",
    },
    "Sunan Ibn Majah": {
        "The Book of the Sunnah": "كتاب المقدمة",
        "The Book of Purification and its Sunnah": "كتاب الطهارة وسننها",
        "The Book of the Prayer": "كتاب الصلاة",
        "The Book of the Adhan and the Sunnah Regarding It": "كتاب الأذان والسنة فيها",
        "The Book On The Mosques And The Congregations": "كتاب المساجد والجماعات",
        "Establishing the Prayer and the Sunnah Regarding Them": "كتاب إقامة الصلاة والسنة فيها",
        "Chapters Regarding Funerals": "كتاب الجنائز",
        "Fasting": "كتاب الصيام",
        "The Chapters Regarding Zakat": "كتاب الزكاة",
        "The Chapters on Marriage": "كتاب النكاح",
        "The Chapters on Divorce": "كتاب الطلاق",
        "The Chapters on Expiation": "كتاب الكفارات",
        "The Chapters on Business Transactions": "كتاب التجارات",
        "The Chapters on Rulings": "كتاب الأحكام",
        "The Chapters on Gifts": "كتاب الهبات",
        "The Chapters on Charity": "كتاب الصدقات",
        "The Chapters on Pawning": "كتاب الرهون",
        "The Chapters on Pre-emption": "كتاب الشفعة",
        "The Chapters on Lost Property": "كتاب اللقطة",
        "The Chapters on Manumission (of Slaves)": "كتاب العتق",
        "The Chapters on Legal Punishments": "كتاب الحدود",
        "The Chapters on Blood Money": "كتاب الديات",
        "The Chapters on Wills": "كتاب الوصايا",
        "Chapters on Shares of Inheritance": "كتاب الفرائض",
        "The Chapters on Jihad": "كتاب الجهاد",
        "Chapters on Hajj Rituals": "كتاب المناسك",
        "Chapters on Sacrifices": "كتاب الأضاحي",
        "Chapters on Slaughtering": "كتاب الذبائح",
        "Chapters on Hunting": "كتاب الصيد",
        "Chapters on Food": "كتاب الأطعمة",
        "Chapters on Drinks": "كتاب الأشربة",
        "Chapters on Medicine": "كتاب الطب",
        "Chapters on Dress": "كتاب اللباس",
        "Etiquette": "كتاب الأدب",
        "Supplication": "كتاب الدعاء",
        "Interpretation of Dreams": "كتاب تعبير الرؤيا",
        "Tribulations": "كتاب الفتن",
        "Zuhd": "كتاب الزهد",
    },
    "Muwatta Malik": {
        "The Times of Prayer": "كتاب وقوت الصلاة",
        "Purity": "كتاب الطهارة",
        "Prayer": "كتاب الصلاة",
        "Forgetfulness in Prayer": "كتاب السهو",
        "Jumu'a": "كتاب الجمعة",
        "Prayer in Ramadan": "كتاب الصلاة فى رمضان",
        "Tahajjud": "كتاب صلاة الليل",
        "Prayer in Congregation": "كتاب صلاة الجماعة",
        "Shortening the Prayer": "كتاب قصر الصلاة فى السفر",
        "The Two 'Ids": "كتاب العيدين",
        "The Fear Prayer": "كتاب صلاة الخوف",
        "The Eclipse Prayer": "كتاب صلاة الكسوف",
        "Asking for Rain": "كتاب الاستسقاء",
        "The Qibla": "كتاب القبلة",
        "The Qur'an": "كتاب القرآن",
        "Burials": "كتاب الجنائز",
        "Zakat": "كتاب الزكاة",
        "Fasting": "كتاب الصيام",
        "I'tikaf in Ramadan": "كتاب الاعتكاف",
        "Hajj": "كتاب الحج",
        "Jihad": "كتاب الجهاد",
        "Vows and Oaths": "كتاب النذور والأيمان",
        "Sacrificial Animals": "كتاب الضحايا",
        "Slaughtering Animals": "كتاب الذبائح",
        "Game": "كتاب الصيد",
        "The 'Aqiqa": "كتاب العقيقة",
        "Fara'id": "كتاب الفرائض",
        "Marriage": "كتاب النكاح",
        "Divorce": "كتاب الطلاق",
        "Suckling": "كتاب الرضاع",
        "Business Transactions": "كتاب البيوع",
        "Qirad": "كتاب القراض",
        "Sharecropping": "كتاب المساقاة",
        "Renting Land": "كتاب كراء الأرض",
        "Pre-emption in Property": "كتاب الشفعة",
        "Judgements": "كتاب الأقضية",
        "Wills and Testaments": "كتاب الوصية",
        "Setting Free and Wala'": "كتاب العتق والولاء",
        "The Mukatab": "كتاب المكاتب",
        "The Mudabbar": "كتاب المدبر",
        "Hudud": "كتاب الحدود",
        "Drinks": "كتاب الأشربة",
        "Blood-Money": "كتاب العقول",
        "The Oath of Qasama": "كتاب القسامة",
        "Madina": "كتاب الْمَدِينَةِ",
        "The Decree": "كتاب القدر",
        "Good Character": "كتاب حسن الخلق",
        "Dress": "كتاب اللباس",
        "The Description of the Prophet, may Allah Bless Him and Grant Him Peace": "كتاب صفة النبى صلى الله عليه وسلم",
        "The Evil Eye": "كتاب العين",
        "Hair": "كتاب الشعر",
        "Visions": "كتاب الرؤيا",
        "Greetings": "كتاب السلام",
        "General Subjects": "كتاب الاستئذان",
        "The Oath of Allegiance": "كتاب البيعة",
        "Speech": "كتاب الكلام",
        "Jahannam": "كتاب جهنم",
        "Sadaqa": "كتاب الصدقة",
        "Knowledge": "كتاب العلم",
        "The Supplication of the Unjustly Wronged": "كتاب دعوة المظلوم",
        "The Names of the Prophet, may Allah Bless Him and Grant Him Peace": "كتاب أسماء النبى صلى الله عليه وسلم",
    },
    "Musnad Ahmad": {
        "Musnad Abu Bakr as-Siddiq (ra)": "مُسْنَدُ أَبِي بَكْرٍ الصِّدِّيقِ رَضِيَ اللَّهُ عَنْهُ",
        "Musnad `Umar b. al-Khattab (ra)": "مُسْنَدِ عُمَرَ بْنِ الْخَطَّابِ رَضِيَ اللَّهُ عَنْهُ",
        "The Hadeeth of Saqeefah": "حَدِيثُ السَّقِيفَةِ",
        "Musnad Uthman ibn Affan": "مُسْنَدُ عُثْمَانَ بْنِ عَفَّانَ رَضِيَ اللَّهُ عَنْهُ",
        "Musnad 'Ali Ibn Abi Talib": "وَمِنْ مُسْنَدِ عَلِيِّ بْنِ أَبِي طَالِبٍ رَضِيَ اللَّهُ عَنْهُ",
        "Musnad of Abu Muhammad Talhah bin 'Ubaidullah": "مُسْنَدُ أَبِي مُحَمَّدٍ طَلْحَةَ بْنِ عُبَيْدِ اللَّهِ رَضِيَ اللَّهُ تَعَالَى عَنْهُ",
        "The Musnad of az-Zubair bin al-'Awwam": "مُسْنَدُ الزُّبَيْرِ بْنِ الْعَوَّامِ رَضِيَ اللَّهُ عَنْهُ",
        "Musnad Abu Ishaq Sa'd bin Abi Waqqas": "",
        "Musnad of Sa'eed bin Zaid bin 'Amr bin Nufail": "",
        "Musnad of 'Abdur-Rahman bin 'Awf az-Zuhri": "",
        "Hadeeth of Abu 'Ubaidah bin al-Jarrah, whose name was 'Amir bin Abdullah": "",
        "The Hadeeth of 'Abdur-Rahman bin Abi Bakr": "",
        "Hadeeth of Zaid bin Kharijah": "",
        "The Hadeeth of al-Harith bin Khazamah": "",
        "Hadeeth of Sa'd, the freed slave of Abu Bakr": "",
        "The Musnad of Ahlul-Bayt & Hadeeth of al-Hasan bin 'Ali bin Abu Talib": "",
        "The hadeeth of Al-Husain bin 'Ali": "",
        "Hadeeth of 'Aqeel bin Abi Talib": "",
        "Hadeeth of Ja'far bin Abi Talib & It is Hadeeth of al-Hijrah (migration)": "",
        "Hadeeth of 'Abdullah bin Ja'far bin Abi Talib": "",
        "Musnad Bani Hashim (Hadeeth of al-'Abbas bin 'Abdul-Muttalib from the  Prophet)": "",
        "Musnad of al-Fadl bin 'Abbas & narrating from the Prophet": "",
        "Hadeeth of Tammam bin al-'Abbas bin 'Abdul-Muttalib from the Prophet": "",
        "Hadeeth of 'Ubaidullah bin al-'Abbas & from the Prophet": "",
        "Musnad of 'Abdullah bin al-'Abbas bin 'Abdul-Muttalib from the Prophet": "",
        "Musnad of Abdullah bin Mas'ood": "",
    },
    "Collections of Forty": {
        "Forty Hadith of an-Nawawi": "الأربعون النووية",
        "Forty Hadith Qudsi": "الحديث القدسي",
        "Forty Hadith of Shah Waliullah Dehlawi": "أربعون شاه ولي الله الدهلوي",
    },
    "Riyad as-Salihin": {
        "The Book of Miscellany": "كتاب المقدمات",
        "The Book of Good Manners": "كتاب الأدب",
        "The Book About the Etiquette of Eating": "كتـــــاب أدب الطعام",
        "The Book of Dress": "كتــــاب اللباس",
        "The Book of the Etiquette of Sleeping, Lying and Sitting etc": "كتاب آداب النوم",
        "The Book of Greetings": "كتاب السلام",
        "The Book of Visiting the Sick": "كتاب عيادة المريض وتشييع الميت والصلاة عليه وحضور دفنه",
        "The Book of Etiquette of Traveling": "كتاب آداب السفر",
        "The Book of Virtues": "كتاب الفضائل",
        "The Book of I'tikaf": "كتاب الاعتكاف",
        "The Book of Hajj": "كتاب الحج",
        "The Book of Jihad": "كتاب الجهاد",
        "The Book of Knowledge": "كتاب العلم",
        "The Book of Praise and Gratitude to Allah": "كتاب حمد الله تعالى وشكره",
        "The Book of Supplicating Allah to Exalt the Mention of Allah's Messenger": "كتاب الصلاة على رسول الله صلى الله عليه وسلم",
        "The Book of the Remembrance of Allah": "كتاب الأذكار",
        "The Book of Du'a (Supplications)": "كتاب الدعوات",
        "The Book of the Prohibited actions": "كتاب الأمور المنهي عنها",
        "The Book of Miscellaneous ahadith of Significant Values": "كتاب المنثورات والملح",
        "The Book of Forgiveness": "كتاب الاستغفار",
    },
    "Mishkat al-Masabih": {
        "Author's Introduction": "مقدمة المؤلف",
        "Faith": "كتاب الإيمان",
        "Knowledge": "كتاب العلم",
        "Purification": "كتاب الطهارة",
        "Prayer": "كتاب الصلاة",
        "Funerals": "كتاب الجنائز",
        "Zakat": "كتاب الزكاة",
        "Fasting": "كتاب الصوم",
        "The Excellent Qualities of the Qur'an": "كتاب فضائل القرآن",
        "Supplications": "كتاب الدعوات",
        "The Rites of Pilgrimage": "كتاب المناسك",
        "Business Transactions": "كتاب البيوع",
        "Inheritance and Wills": "كتاب الفرائض والوصايا",
        "Marriage": "كتاب النكاح",
        "Emancipation": "كتاب العتق",
        "Oaths and Vows": "كتاب الإيمان والنذور",
        "Retaliation": "كتاب القصاص",
        "Prescribed Punishments": "كتاب الحدود",
        "The Offices of Commander and Qadi": "كتاب الإمارة والقضاء",
        "Jihad": "كتاب الجهاد",
        "Game and Animals Which May Be Slaughtered": "كتاب الصيد والذبائح",
        "Foods": "كتاب الأطعمة",
        "Clothing": "كتاب اللباس",
        "Medicine and Spells": "كتاب الطب والرقى",
        "Visions": "كتاب الرؤيا",
    },
    "Al-Adab Al-Mufrad": {
        "Parents": "كتاب الْوَالِدَيْنِ",
        "Ties of Kinship": "كتاب صِلَةِ الرَّحِمِ",
        "Mawlas (Clients of Manumission)": "كتاب مَوَالِي",
        "Looking after girls": "كتاب عول البنات",
        "Looking after children": "كتاب رعاية الأولاد",
        "Neighbours": "كتاب الْجَارِ",
        "Generosity and Orphans": "كتاب الْكَرَمِ وَ يَتِيمٌ",
        "Children's Death": "كتاب موت الأولاد",
        "Being a master": "كتاب الملكة",
        "Supervision": "كتاب الرعاية",
        "Good Conduct": "كتاب الْمَعْرُوفِ",
        "Cheerfulness Towards People": "كتاب الِانْبِسَاطِ إِلَى النَّاسِ",
        "Consultation": "كتاب الْمَشُورَةِ",
        "Excellence in Character": "كتاب حسن الخلق",
        "Cursing": "كتاب اللعن",
        "Praise": "كتاب المدح",
        "Visitation": "كتاب الزِّيَارَةِ",
        "The Elderly": "كتاب الأكَابِرِ",
        "Children": "كتاب الصَّغِيرِ",
        "Mercy": "كتاب رَحْمَةِ",
        "Social Behaviour": "كتاب ذات البين",
        "Abandonment": "كتاب الهجر",
        "Advising": "كتاب الإشارة",
        "Disparaging": "كتاب السِّبَابِ",
        "Extravagance in Building": "كتاب السَّرَفِ فِي  الْبِنَاءِ",
        "Compassion": "كتاب الرِّفْقِ",
        "Attending to this world": "كتاب الاعتناء بالدنيا",
        "Injustice": "كتاب الظُّلْم",
        "Visiting the Ill": "كتاب عيادة المرضى",
        "General Behavior": "كتاب التصرف العام",
        "Supplication": "كتاب الدعاء",
        "Guests and Spending": "كتاب الضيف والنفقة",
        "Sayings": "كتاب الأقوال",
        "Names": "كتاب الأسْمَاءِ",
        "Kunyas": "كتاب  الكُنْيَةِ",
        "Poetry": "كتاب الشِّعْرِ",
        "Words": "كتاب الْكَلامِ",
        "Consequences": "كتاب عاقبة الأمور",
        "Omens": "كتاب الطيرة",
        "Sneezing and Yawning": "كتاب الْعُطَاسَ والتثاؤب",
        "Gestures": "كتاب الحركات",
        "Greetings": "كتاب السَّلامِ",
        "Asking Permission": "كتاب الاسْتِئْذَانُ",
        "The People of the Book": "كتاب أَهْلِ الْكِتَابِ",
        "Letters": "كتاب الرَّسَائِلِ\u200f",
        "Gatherings": "كتاب الْمَجَالِسِ",
        "Behaviour with people": "كتاب تعامل الناس",
        "Sitting and lying down": "باب الجلوس والاستلقاء",
        "Mornings and evenings": "كتاب الصباح والمساء",
        "Sleep and night lodging": "كتاب النوم والمبيت",
        "Animals": "كتاب الْبَهَائِمِ",
        "Midday Naps": "كتاب الْقَائِلَةِ",
        "Circumcision": "كتاب الْخِتَانِ",
        "Betting and similar pastimes": "كتاب القمار ونحوه",
        "Recognition": "كتاب المعرفة",
        "Meddling and Harshness": "كتاب الفضول والجفاء",
        "Anger": "كتاب الْغَضَبِ",
    },
    "Ash-Shama'il Al-Muhammadiyah": {
        "The Noble Features Of Rasoolullah": "باب ما جاء في خلق رسول الله صلى الله عليه وسلم",
        "Seal Of Nubuwwah (Prophethood) Of Rasoolullah": "باب ما جاء في خاتم النبوة",
        "The Mubarak Hair Of Rasoolullah": "-باب ما جاء في شعر رسول الله صلى الله عليه وسلم",
        "The Combing Of The Hair Of Rasoolullah": "باب ما جاء في ترجل رسول الله صلى الله عليه وسلم",
        "Appearing Of The White Hair Of Rasoolullah": "باب ما جاء في شيب رسول الله صلى الله عليه وسلم",
        "Rasoolullah Using a Dye": "باب ما جاء في خضاب رسول الله صلى الله عليه وسلم",
        "Kuhl Of Rasoolullah": "باب ما جاء في كُحل رسول الله صلى الله عليه وسلم",
        "The Dressing Of Rasoolullah": "باب ما جاء في لباس رسول الله صلى الله عليه وسلم",
        "The Standard of Living of Rasoolullah": "باب ماجاء في عيش رسول الله صلى الله عليه وسلم",
        "The Khuff (Leather Socks) Of Rasoolullah": "باب ما جاء في خف رسول الله صلى الله عليه وسلم",
        "The Shoes Of Rasoolullah": "باب ماجاء في نعل رسول الله صلى الله عليه وسلم",
        "The Mubarak Ring Of Rasoolullah": "باب ما جاء في ذكر خاتم رسول الله صلى الله عليه وسلم",
        "Stating That Rasoolullah Wore The Ring On His Right Hand": "باب ماجاء في تختم رسول الله صلى الله عليه وسلم",
        "The Sword Of Rasoolullah": "باب ماجاء في صفة سَيْفِ رَسُولِ اللهِ صلى الله عليه وسلم",
        "The Armor Of Rasoolullah": "باب ماجاء في صفة درع رَسُولِ اللهِصلى الله عليه وسلم",
        "The Helmet Of Rasoolullah": "باب ما جاء في صفة مغفر رسول الله صلى الله عليه وسلم",
        "The Turban Of Rasoolullah": "باب ما جاء في عمامة رسول الله صلى الله عليه وسلم",
        "The Lungi Of Rasoolullah": "باب ما جاء في صفة إزار رسول الله صلى الله عليه وسلم",
        "The Walking Of Rasoolullah": "باب ما جاء في مشية رسول الله صلى الله عليه وسلم",
        "The Qinaa Of Rasoolullah": "باب ما جاء في تقنع رسول الله صلى الله عليه وسلم",
        "The Sitting Of Rasoolullah": "باب ما جاء في جلسته صلى الله عليه وسلم",
        "The Pillow Of Rasoolullah": "باب ما جاء في تكأة رسول الله صلى الله عليه وسلم",
        "Rasoolullah Leaning On Something Other Than a Pillow": "باب ما جاء في اتكاء رسول الله صلى الله عليه وسلم",
        "Description Of The Eating Of Rasoolullah": "باب ما جاء في أكل رسول الله صلى الله عليه وسلم",
        "The Bread Of Rasoolullah": "باب ما جاء في صفة خبز رسول الله صلى الله عليه وسلم",
        "What Rasoolullah Would Eat with Bread": "ما جاء في إدام رسول الله صلى الله عليه وسلم",
        "Rasoolullah Performing Wudu At The Time Of Eating": "باب ما جاء في صفة وضوء رسول الله صلى الله عليه وسلم عند الطعام",
        "The Words That Of Rasoolullah Said Before and After Eating": "باب ما جاء في قول رسول الله صلى الله عليه وسلم قبل الطعام وعند الفراغ منه",
        "The Cup Of Rasoolullah": "باب ما جاء في قدح رسول الله صلى الله عليه وسلم",
        "The Fruits Eaten By Rasoolullah": "باب ما جاء في صفة فاكهة رسول الله صلى الله عليه وسلم",
        "Description Of The Things Rasoolullah Drank": "باب ما جاء في صفة شراب رسول الله صلى الله عليه وسلم",
        "Hadith Describing The Manner Rasoolullah Drank": "باب ما جاء في شرب رسول الله صلى الله عليه وسلم",
        "Rasoolullah Using 'Itr": "باب ما جاء في تعطررسول الله صلى الله عليه وسلم",
        "The Speech Of rasoolullah": "باب كيف كان كلام رسول الله صلى الله عليه وسلم",
        "The Laughing Of Rasoolullah": "باب ما جاء في ضحك رسول الله صلى الله عليه وسلم",
        "Description Of The Joking Of Rasoolullah": "باب ما جاء في صفة مزاح رسول الله صلى الله عليه وسلم",
        "Description Of The Saying Of Rasoolullah On Poetry": "باب ما جاء في صفة كلام رسول الله صلى الله عليه وسلم في الشعر",
        "Story Telling Of Rasoolullah At Night": "باب ما جاء في كلام رسول الله صلى الله عليه وسلم في السمر",
        "Hadith of Umm Zar`": "حديث أم زرع",
        "The Sleeping Of Rasoolullah": "باب في صفة نوم رسول الله صلى الله عليه وسلم في السمر",
        "Worship And Devotion Of Rasoolullah": "باب ما جاء في عبادة النبي صلى الله عليه وسلم",
        "Salaatut Duha (Chaast Prayers)": "باب صلاة الضحى",
        "Sayyidina Rasoolullah Performing Nawaafil At Home": "باب صلاة التطوع في البيت",
        "The Fasting Of Sayyidina Rasoolullah": "باب ماجاء في صوم رسول الله صلى الله عليه وسلم",
        "The Recital Of Sayyidina Rasoolullah": "باب ماجاء في قراءة رسول الله صلى الله عليه وسلم",
        "The Weeping Of Sayyidina Rasoolullah": "باب ماجاء في بكاء رسول الله صلى الله عليه وسلم",
        "Narrations Of The Bed Of Sayyidina Rasoolullah": "باب ماجاء في فراش رسول الله صلى الله عليه وسلم",
        "The Humbleness Of Sayyidina Rasoolullah": "باب ماجاء في تواضع رسول الله صلى الله عليه وسلم",
        "Noble Character And Habits Of Sayyidina Rasoolullah": "باب ماجاء في خلق رسول الله صلى الله عليه وسلم",
        "Modesty Of Sayyidina Rasoolullah": "باب ماجاء في حياء رسول الله صلى الله عليه وسلم",
        "Hajaamah (Cupping-Cautering) Of Sayyidina Rasoolullah": "باب ماجاء في حجامة رسول الله صلى الله عليه وسلم",
        "The Names Of Sayyidina Rasoolullah": "باب ماجاء في أسماء رسول الله صلى الله عليه وسلم",
        "The Living Of Sayyidina Rasoolullah": "باب ماجاء في عيش رسول الله صلى الله عليه وسلم",
        "The Noble Age Of Sayyidina Rasoolullah": "باب ماجاء في سن رسول الله صلى الله عليه وسلم",
        "The Death Of Sayyidina Rasoolullah": "باب ماجاء في وفاة رسول الله صلى الله عليه وسلم",
        "The Legacy Of Sayyidina Rasoolullah": "باب ماجاء في ميراث رسول الله صلى الله عليه وسلم",
        "The Seeing Of Rasoolullah In a Dream": "باب ماجاء في رؤية رسول الله صلى الله عليه وسلم",
    },
    "Bulugh al-Maram": {
        "The Book of Purification": "كتاب الطهارة",
        "The Book of Prayer": "كتاب الصلاة",
        "Funerals": "كتاب الجنائز",
        "The Book of Zakah": "كتاب الزكاة",
        "Fasting": "كتاب الصيام",
        "Hajj": "كتاب الحج",
        "Business Transactions": "كتاب البيوع",
        "Marriage": "كتاب النكاح",
        "Crimes (Qisas or Retaliation)": "كتاب الجنايات",
        "Hudud": "كتاب الحدود",
        "Jihad": "كتاب الجهاد",
        "Food": "كتاب الأطعمة",
        "Oaths and Vows": "كتاب الأيمان والنذور",
        "Judgments": "كتاب القضاء",
        "Emancipation": "كتاب العتق",
        "The Comprehensive Book": "كتاب الجامع",
    },
    "Hisn al-Muslim": {"Fortress of the Muslim (Hisn al-Muslim)": "حصن المسلم"},
    "Musnad Imam Abu Hanifa": {
        "The Book of Faith, Islam, Destiny, and Intercession": "كتاب الإيمان والإسلام والقدر والشفاعة",
        "The Book of Knowledge": "كتاب العلم",
        "The Book of Purifications": "كتاب الطهارات",
        "The Book of Prayer ": "كتاب الصلاة",
        "The Book of Zakat": "كتاب الزكاة",
        "The Book of Fasting": "كتاب الصوم",
        "The Book of Hajj": "كتاب الحج",
        "The Book of Marriage": "كتاب النكاح",
        "The Book of Istibra": "كتاب الاستبراء",
        "The Book of Breastfeeding": "كتاب الرضاع",
        "The Book of Divorce": "كتاب الطلاق",
        "The Book of Expenses": "كتاب النفقات",
        "The Book of Management and Loyalty": "كتاب التدبير والولاء",
        "The Book of Faith": "كتاب الأيمان",
        "The Book of Borders": "كتاب الحدود",
        "The Book of Jihad": "كتاب الجهاد والسير",
        "The Book of Sales": "كتاب البيوع",
        "The Book of Mortgage": "كتاب الرهن",
        "The Book of Pre-emption": "كتاب الشفعة",
        "The Book of Farmers": "كتاب المزارعة",
        "The Book of Virtues and Excellence": "كتاب الفضائل والشمائل",
        "The book of the virtues of Ummah of Prophet": "كتاب فضل أمته رضي الله عنه",
        "The Book of Foods, Drinks, Drinking, Victims, Hunting, and Sacrifices": "كتاب الأطعمة والأشربة والشرب والضحايا والصيد والذبائح",
        "The Book of Dress and Adornment": "كتاب اللباس والزينة",
        "The Book of Medicine, the Virtue of Sickness, Ruqyah, and Supplications": "كتاب الطب وفضل المرض والرقى والدعوات",
        "The Book of Literature": "كتاب الأدب",
        "The Book of Ruqqaq": "كتاب الرقاق",
        "The Book of Crimes": "كتاب الجنايات",
        "The Book of Rulings": "كتاب الأحكام",
        "The Book of Trials": "كتاب الفتن",
        "The Book of Interpretation": "كتاب التفسير",
        "The Book of Commandments and Obligations": "كتاب الوصايا والفرائض",
        "The Book of Resurrection and the Description of Paradise": "كتاب القيامة وصفة الجنة"
    }
}
